// <auto-generated />
using System;
using Fundamental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundamental.Migrations.Fundamental
{
    [DbContext(typeof(FundamentalDbContext))]
    [Migration("20231125173931_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fundamental.Domain.Prices.Entities.ClosePrice", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"), 1L, 1);

                    b.Property<long>("Close")
                        .HasColumnType("bigint")
                        .HasColumnName("Close")
                        .HasColumnOrder(4);

                    b.Property<long>("CloseAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("CloseAdjusted")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date")
                        .HasColumnOrder(3);

                    b.Property<long>("High")
                        .HasColumnType("bigint")
                        .HasColumnName("High")
                        .HasColumnOrder(6);

                    b.Property<long>("HighAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("HighAdjusted")
                        .HasColumnOrder(11);

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("Last")
                        .HasColumnType("bigint")
                        .HasColumnName("Last")
                        .HasColumnOrder(8);

                    b.Property<long>("LastAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("LastAdjusted")
                        .HasColumnOrder(13);

                    b.Property<long>("Low")
                        .HasColumnType("bigint")
                        .HasColumnName("Low")
                        .HasColumnOrder(7);

                    b.Property<long>("LowAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("LowAdjusted")
                        .HasColumnOrder(12);

                    b.Property<long>("Open")
                        .HasColumnType("bigint")
                        .HasColumnName("Open")
                        .HasColumnOrder(5);

                    b.Property<long>("OpenAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("OpenAdjusted")
                        .HasColumnOrder(10);

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("Quantity")
                        .HasColumnOrder(15);

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("Value")
                        .HasColumnOrder(16);

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("Volume")
                        .HasColumnOrder(14);

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SymbolId");

                    b.HasIndex("Date", "SymbolId")
                        .IsUnique();

                    b.ToTable("ClosePrice", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.Symbol", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"), 1L, 1);

                    b.Property<string>("CompanyEnCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyEnCode");

                    b.Property<string>("CompanyIsin")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyIsin");

                    b.Property<string>("CompanyPersianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyPersianName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EnName");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Isin");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint")
                        .HasColumnName("MarketCap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<short>("ProductType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ProductType")
                        .HasDefaultValueSql("1");

                    b.Property<string>("SectorCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SectorCode");

                    b.Property<string>("SubSectorCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SubSectorCode");

                    b.Property<string>("SymbolEnName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SymbolEnName");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.Property<string>("TseInsCode")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("TseInsCode");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Isin")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Symbol", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.SymbolRelation", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"), 1L, 1);

                    b.Property<long>("ChildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<double>("Ratio")
                        .HasColumnType("float")
                        .HasColumnName("Ratio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id");

                    b.HasIndex("ChildId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("SymbolRelations", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Prices.Entities.ClosePrice", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.SymbolRelation", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Child")
                        .WithMany("InvestorSymbols")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Parent")
                        .WithMany("InvestmentSymbols")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.Symbol", b =>
                {
                    b.Navigation("InvestmentSymbols");

                    b.Navigation("InvestorSymbols");
                });
#pragma warning restore 612, 618
        }
    }
}
