// <auto-generated />
using System;
using System.Collections.Generic;
using Fundamental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundamental.Migrations.Fundamental
{
    [DbContext(typeof(FundamentalDbContext))]
    [Migration("20231227041237_AddPublisherTable")]
    partial class AddPublisherTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fundamental.Domain.Codals.FinancialStatement", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Currency")
                        .IsFixedLength();

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("TraceNo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)")
                        .HasColumnName("Uri");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.FinancialStatement.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("FiscalYear");
                        });

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SymbolId");

                    b.ToTable("FinancialStatements", "fs");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheet", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<short>("CodalCategory")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("CodalRow")
                        .HasColumnType("SMALLINT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Currency")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsAudited")
                        .HasColumnType("bit");

                    b.Property<short>("Row")
                        .HasColumnType("SMALLINT");

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("TraceNo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)")
                        .HasColumnName("Uri");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheet.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("FiscalYear");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheet.Value#SignedMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("Value");
                        });

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SymbolId");

                    b.ToTable("BalanceSheet", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheetSort", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<short>("Category")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("Category");

                    b.Property<short>("CodalRow")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("CodalRow");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<short>("Order")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("Order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Order")
                        .IsUnique();

                    b.HasIndex("Category", "CodalRow")
                        .IsUnique();

                    b.ToTable("BalanceSheetSort", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatement", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<int>("CodalCategory")
                        .HasColumnType("int");

                    b.Property<int>("CodalRow")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Currency")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsAudited")
                        .HasColumnType("bit");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("TraceNo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)")
                        .HasColumnName("Uri");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatement.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("FiscalYear");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatement.Value#SignedMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("Value");
                        });

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SymbolId");

                    b.ToTable("IncomeStatement", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatementSort", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<short>("CodalRow")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("CodalRow");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<short>("Order")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("Order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("IncomeStatementSort", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Currency")
                        .IsFixedLength();

                    b.Property<bool>("HasSubCompanySale")
                        .HasColumnType("bit");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("TraceNo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)")
                        .HasColumnName("Uri");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("FiscalYear");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ReportMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.ReportMonth#StatementMonth", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("ReportMonth");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SaleBeforeCurrentMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.SaleBeforeCurrentMonth#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("SaleBeforeCurrentMonth");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SaleCurrentMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.SaleCurrentMonth#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("SaleCurrentMonth");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SaleIncludeCurrentMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.SaleIncludeCurrentMonth#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("SaleIncludeCurrentMonth");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SaleLastYear", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.SaleLastYear#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("SaleLastYear");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("YearEndMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.YearEndMonth#StatementMonth", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("YearEndMonth");
                        });

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SymbolId");

                    b.ToTable("MonthlyActivities", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.NonOperationIncomeAndExpense", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Currency")
                        .IsFixedLength();

                    b.Property<bool>("CurrentPeriod")
                        .HasColumnType("BIT")
                        .HasColumnName("CurrentPeriod");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("ForecastPeriod")
                        .HasColumnType("BIT")
                        .HasColumnName("ForecastPeriod");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsAudited")
                        .HasColumnType("BIT")
                        .HasColumnName("IsAudited");

                    b.Property<bool>("PreviousPeriod")
                        .HasColumnType("BIT")
                        .HasColumnName("PreviousPeriod");

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("TraceNo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)")
                        .HasColumnName("Uri");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.Manufacturing.Entities.NonOperationIncomeAndExpense.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("FiscalYear");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Fundamental.Domain.Codals.Manufacturing.Entities.NonOperationIncomeAndExpense.Value#SignedMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("Value");
                        });

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SymbolId");

                    b.ToTable("NonOperationIncomeAndExpense", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Publisher", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<string>("ActivitySubject")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AuditorName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CodalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Currency")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ExecutiveManager")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FactoryFax")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FactoryTel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FaxNo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FinancialManager")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FinancialYear")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FundType")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<string>("Inspector")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("IsEnableSubCompany")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupplied")
                        .HasColumnType("bit");

                    b.Property<string>("Isic")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("MarketType")
                        .HasColumnType("int");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("OfficeAddress")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("OfficeFax")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OfficeTel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("ParentSymbolId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReportingType")
                        .HasColumnType("int");

                    b.Property<string>("ShareOfficeAddress")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ShareOfficeFax")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ShareOfficeTel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("SubCompanyType")
                        .HasColumnType("int");

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelNo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.ComplexProperty<Dictionary<string, object>>("ListedCapital", "Fundamental.Domain.Codals.Publisher.ListedCapital#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("ListedCapital");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnauthorizedCapital", "Fundamental.Domain.Codals.Publisher.UnauthorizedCapital#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("UnauthorizedCapital");
                        });

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentSymbolId");

                    b.HasIndex("SymbolId");

                    b.ToTable("Publisher");
                });

            modelBuilder.Entity("Fundamental.Domain.Prices.Entities.ClosePrice", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<long>("Close")
                        .HasColumnType("bigint")
                        .HasColumnName("Close")
                        .HasColumnOrder(4);

                    b.Property<long>("CloseAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("CloseAdjusted")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date")
                        .HasColumnOrder(3);

                    b.Property<long>("High")
                        .HasColumnType("bigint")
                        .HasColumnName("High")
                        .HasColumnOrder(6);

                    b.Property<long>("HighAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("HighAdjusted")
                        .HasColumnOrder(11);

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("Last")
                        .HasColumnType("bigint")
                        .HasColumnName("Last")
                        .HasColumnOrder(8);

                    b.Property<long>("LastAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("LastAdjusted")
                        .HasColumnOrder(13);

                    b.Property<long>("Low")
                        .HasColumnType("bigint")
                        .HasColumnName("Low")
                        .HasColumnOrder(7);

                    b.Property<long>("LowAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("LowAdjusted")
                        .HasColumnOrder(12);

                    b.Property<long>("Open")
                        .HasColumnType("bigint")
                        .HasColumnName("Open")
                        .HasColumnOrder(5);

                    b.Property<long>("OpenAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("OpenAdjusted")
                        .HasColumnOrder(10);

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("Quantity")
                        .HasColumnOrder(15);

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("Value")
                        .HasColumnOrder(16);

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("Volume")
                        .HasColumnOrder(14);

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SymbolId");

                    b.HasIndex("Date", "SymbolId")
                        .IsUnique();

                    b.ToTable("ClosePrice", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.Symbol", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<string>("CompanyEnCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyEnCode");

                    b.Property<string>("CompanyIsin")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyIsin");

                    b.Property<string>("CompanyPersianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyPersianName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EnName");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsUnOfficial")
                        .HasColumnType("bit");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Isin");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint")
                        .HasColumnName("MarketCap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<short>("ProductType")
                        .HasColumnType("smallint")
                        .HasColumnName("ProductType");

                    b.Property<string>("SectorCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SectorCode");

                    b.Property<string>("SubSectorCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SubSectorCode");

                    b.Property<string>("SymbolEnName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SymbolEnName");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.Property<string>("TseInsCode")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("TseInsCode");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Isin")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Symbol", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.SymbolRelation", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"));

                    b.Property<long>("ChildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<double>("Ratio")
                        .HasColumnType("float")
                        .HasColumnName("Ratio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id");

                    b.HasIndex("ChildId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("SymbolRelations", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.FinancialStatement", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.Money", "Asset", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("Asset");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.Money", "BankInterestIncome", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("BankInterestIncome");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.Money", "Expense", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("Expense");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.SignedMoney", "GrossProfit", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("GrossProfit");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.SignedMoney", "InvestmentIncome", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("InvestmentIncome");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.Money", "NetProfit", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("NetProfit");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.Money", "OperatingIncome", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("OperatingIncome");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.SignedMoney", "OperatingProfit", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("OperatingProfit");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.Money", "OwnersEquity", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("OwnersEquity");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Common.ValueObjects.Money", "Receivables", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("Receivables");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "ReportMonth", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("ReportMonth");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "YearEndMonth", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("YearEndMonth");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("FinancialStatements", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id");
                        });

                    b.Navigation("Asset")
                        .IsRequired();

                    b.Navigation("BankInterestIncome")
                        .IsRequired();

                    b.Navigation("Expense")
                        .IsRequired();

                    b.Navigation("GrossProfit")
                        .IsRequired();

                    b.Navigation("InvestmentIncome")
                        .IsRequired();

                    b.Navigation("NetProfit")
                        .IsRequired();

                    b.Navigation("OperatingIncome")
                        .IsRequired();

                    b.Navigation("OperatingProfit")
                        .IsRequired();

                    b.Navigation("OwnersEquity")
                        .IsRequired();

                    b.Navigation("Receivables")
                        .IsRequired();

                    b.Navigation("ReportMonth")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("YearEndMonth")
                        .IsRequired();
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheet", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "ReportMonth", b1 =>
                        {
                            b1.Property<long>("BalanceSheet_id")
                                .HasColumnType("bigint");

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("ReportMonth");

                            b1.HasKey("BalanceSheet_id");

                            b1.ToTable("BalanceSheet", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("BalanceSheet_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "YearEndMonth", b1 =>
                        {
                            b1.Property<long>("BalanceSheet_id")
                                .HasColumnType("bigint");

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("YearEndMonth");

                            b1.HasKey("BalanceSheet_id");

                            b1.ToTable("BalanceSheet", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("BalanceSheet_id");
                        });

                    b.Navigation("ReportMonth")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("YearEndMonth")
                        .IsRequired();
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatement", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "ReportMonth", b1 =>
                        {
                            b1.Property<long>("IncomeStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("ReportMonth");

                            b1.HasKey("IncomeStatement_id");

                            b1.ToTable("IncomeStatement", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("IncomeStatement_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "YearEndMonth", b1 =>
                        {
                            b1.Property<long>("IncomeStatement_id")
                                .HasColumnType("bigint");

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("YearEndMonth");

                            b1.HasKey("IncomeStatement_id");

                            b1.ToTable("IncomeStatement", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("IncomeStatement_id");
                        });

                    b.Navigation("ReportMonth")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("YearEndMonth")
                        .IsRequired();
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.NonOperationIncomeAndExpense", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "ReportMonth", b1 =>
                        {
                            b1.Property<long>("NonOperationIncomeAndExpense_id")
                                .HasColumnType("bigint");

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("ReportMonth");

                            b1.HasKey("NonOperationIncomeAndExpense_id");

                            b1.ToTable("NonOperationIncomeAndExpense", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("NonOperationIncomeAndExpense_id");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "YearEndMonth", b1 =>
                        {
                            b1.Property<long>("NonOperationIncomeAndExpense_id")
                                .HasColumnType("bigint");

                            b1.Property<byte>("Month")
                                .HasColumnType("TINYINT")
                                .HasColumnName("YearEndMonth");

                            b1.HasKey("NonOperationIncomeAndExpense_id");

                            b1.ToTable("NonOperationIncomeAndExpense", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("NonOperationIncomeAndExpense_id");
                        });

                    b.Navigation("ReportMonth")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("YearEndMonth")
                        .IsRequired();
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Publisher", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "ParentSymbol")
                        .WithMany()
                        .HasForeignKey("ParentSymbolId");

                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentSymbol");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Fundamental.Domain.Prices.Entities.ClosePrice", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.SymbolRelation", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Child")
                        .WithMany("InvestorSymbols")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Parent")
                        .WithMany("InvestmentSymbols")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.Symbol", b =>
                {
                    b.Navigation("InvestmentSymbols");

                    b.Navigation("InvestorSymbols");
                });
#pragma warning restore 612, 618
        }
    }
}
