using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Fundamental.Migrations.Fundamental
{
    /// <inheritdoc />
    public partial class AddSectorEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create sector table if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS shd.sector (
                    _id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Id"" uuid NOT NULL,
                    name character varying(100) NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ModifiedAt"" timestamp with time zone
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ix_sector_id ON shd.sector (""Id"");
                CREATE INDEX IF NOT EXISTS ix_sector_name ON shd.sector (name);
            ");

            // Add sector_id column to symbol table if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'shd'
                        AND table_name = 'symbol'
                        AND column_name = 'sector_id'
                    ) THEN
                        ALTER TABLE shd.symbol ADD COLUMN sector_id bigint;
                    END IF;
                END $$;
            ");

            // Create index on sector_id if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ix_symbol_sector_id ON shd.symbol (sector_id);
            ");

            // Add foreign key if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.table_constraints
                        WHERE constraint_name = 'fk_symbol_sector_sector_id'
                        AND table_schema = 'shd'
                    ) THEN
                        ALTER TABLE shd.symbol
                            ADD CONSTRAINT fk_symbol_sector_sector_id
                            FOREIGN KEY (sector_id) REFERENCES shd.sector(_id)
                            ON DELETE NO ACTION;
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE shd.symbol DROP CONSTRAINT IF EXISTS fk_symbol_sector_sector_id;
                DROP INDEX IF EXISTS shd.ix_symbol_sector_id;
                ALTER TABLE shd.symbol DROP COLUMN IF EXISTS sector_id;
                DROP TABLE IF EXISTS shd.sector;
            ");
        }
    }
}
