// <auto-generated />
using System;
using System.Collections.Generic;
using Fundamental.Domain.Common.Enums;
using Fundamental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fundamental.Migrations.Fundamental
{
    [DbContext(typeof(FundamentalDbContext))]
    partial class FundamentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "company_type", new[] { "none_financial_institution", "public_investment_and_holding", "financial_institutions", "subsidiary_financial_institutions", "intermediary_institutions", "investment_funds", "basket_companies", "investment_advisory_companies", "financial_information_processing_companies", "capital_supply_companies", "associations", "central_asset_management_company", "rating_institutions", "article44", "brokers", "government_companies", "exempt_companies", "un_known1" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enable_sub_company", new[] { "in_active", "active", "accepted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "iso_currency", new[] { "irr", "usd", "eur" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "publisher_fund_type", new[] { "un_known", "not_a_fund", "real_estate", "fixed_income", "mixed", "equity", "project", "venture", "market_making", "commodity", "diversified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "publisher_market_type", new[] { "none", "first", "second", "base", "small_and_medium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "publisher_state", new[] { "register_in_ime", "register_in_irenex", "register_in_tse", "register_in_ifb", "registered_not_accepted", "not_registered" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "publisher_sub_company_type", new[] { "un_known", "normal", "liquidation", "has_foreign_currency_unit", "has_foreign_currency_unit_and_foreign_auditor", "un_known1", "un_known2", "un_known3", "un_known4", "un_known5", "un_known6" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reporting_type", new[] { "production", "structural", "investment", "bank", "leasing", "services", "insurance", "maritime_transportation", "agriculture", "capital_provision", "un_known" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fundamental.Domain.Codals.FinancialStatement", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<IsoCurrency>("Currency")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("iso_currency")
                        .HasColumnName("currency");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("trace_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("Uri");

                    b.Property<long>("symbol_id")
                        .HasColumnType("bigint")
                        .HasColumnName("symbol_id");

                    b.ComplexProperty<Dictionary<string, object>>("Asset", "Fundamental.Domain.Codals.FinancialStatement.Asset#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("asset");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("BankInterestIncome", "Fundamental.Domain.Codals.FinancialStatement.BankInterestIncome#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("bank_interest_income");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Expense", "Fundamental.Domain.Codals.FinancialStatement.Expense#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("expense");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.FinancialStatement.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("fiscal_year");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("GrossProfit", "Fundamental.Domain.Codals.FinancialStatement.GrossProfit#SignedCodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("gross_profit");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("InvestmentIncome", "Fundamental.Domain.Codals.FinancialStatement.InvestmentIncome#SignedCodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("investment_income");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NetProfit", "Fundamental.Domain.Codals.FinancialStatement.NetProfit#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("net_profit");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("OperatingIncome", "Fundamental.Domain.Codals.FinancialStatement.OperatingIncome#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("operating_income");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("OperatingProfit", "Fundamental.Domain.Codals.FinancialStatement.OperatingProfit#SignedCodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("operating_profit");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("OwnersEquity", "Fundamental.Domain.Codals.FinancialStatement.OwnersEquity#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("owners_equity");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Receivables", "Fundamental.Domain.Codals.FinancialStatement.Receivables#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("receivables");
                        });

                    b.HasKey("_id")
                        .HasName("pk_financial_statement");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_statement_id");

                    b.HasIndex("symbol_id")
                        .HasDatabaseName("ix_financial_statement_symbol_id");

                    b.ToTable("financial-statement", "fs");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheet", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<short>("CodalCategory")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("codal_category");

                    b.Property<short>("CodalRow")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("codal_row");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<IsoCurrency>("Currency")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("iso_currency")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsAudited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_audited");

                    b.Property<short>("Row")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("row");

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("trace_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("uri");

                    b.Property<long>("symbol-id")
                        .HasColumnType("bigint")
                        .HasColumnName("symbol_id");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheet.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("fiscal-year");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheet.Value#SignedCodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("value");
                        });

                    b.HasKey("_id")
                        .HasName("pk_balance_sheet");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_balance_sheet_id");

                    b.HasIndex("symbol-id")
                        .HasDatabaseName("ix_balance_sheet_symbol_id");

                    b.ToTable("balance-sheet", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheetSort", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<short>("Category")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("category");

                    b.Property<short>("CodalRow")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("codal_row");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<short>("Order")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id")
                        .HasName("pk_balance_sheet_sort");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_balance_sheet_sort_id");

                    b.HasIndex("Order")
                        .IsUnique()
                        .HasDatabaseName("ix_balance_sheet_sort_order");

                    b.HasIndex("Category", "CodalRow")
                        .IsUnique()
                        .HasDatabaseName("ix_balance_sheet_sort_category_codal_row");

                    b.ToTable("balance-sheet-sort", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatement", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<int>("CodalCategory")
                        .HasColumnType("integer")
                        .HasColumnName("codal_category");

                    b.Property<int>("CodalRow")
                        .HasColumnType("integer")
                        .HasColumnName("codal_row");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<IsoCurrency>("Currency")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("iso_currency")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsAudited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_audited");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("trace_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("uri");

                    b.Property<long>("symbol-id")
                        .HasColumnType("bigint")
                        .HasColumnName("symbol_id");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatement.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("fiscal-year");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatement.Value#SignedCodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("value");
                        });

                    b.HasKey("_id")
                        .HasName("pk_income_statement");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_income_statement_id");

                    b.HasIndex("symbol-id")
                        .HasDatabaseName("ix_income_statement_symbol_id");

                    b.ToTable("income-statement", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatementSort", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<short>("CodalRow")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("codal_row");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<short>("Order")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id")
                        .HasName("pk_income_statement_sort");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_income_statement_sort_id");

                    b.HasIndex("Order")
                        .IsUnique()
                        .HasDatabaseName("ix_income_statement_sort_order");

                    b.ToTable("income-statement-sort", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<IsoCurrency>("Currency")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("iso_currency")
                        .HasColumnName("currency");

                    b.Property<bool>("HasSubCompanySale")
                        .HasColumnType("boolean")
                        .HasColumnName("has_sub_company_sale");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("trace_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("uri");

                    b.Property<long>("symbol_id")
                        .HasColumnType("bigint")
                        .HasColumnName("symbol_id");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("fiscal_year");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ReportMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.ReportMonth#StatementMonth", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("report_month");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SaleBeforeCurrentMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.SaleBeforeCurrentMonth#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("sale_before_current_month");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SaleCurrentMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.SaleCurrentMonth#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("sale_current_month");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SaleIncludeCurrentMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.SaleIncludeCurrentMonth#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("sale_include_current_month");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SaleLastYear", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.SaleLastYear#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("sale_last_year");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("YearEndMonth", "Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity.YearEndMonth#StatementMonth", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("year_end_month");
                        });

                    b.HasKey("_id")
                        .HasName("pk_monthly_activity");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_monthly_activity_id");

                    b.HasIndex("symbol_id")
                        .HasDatabaseName("ix_monthly_activity_symbol_id");

                    b.ToTable("monthly-activity", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.NonOperationIncomeAndExpense", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<IsoCurrency>("Currency")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("iso_currency")
                        .HasColumnName("currency");

                    b.Property<bool>("CurrentPeriod")
                        .HasColumnType("boolean")
                        .HasColumnName("current_period");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("ForecastPeriod")
                        .HasColumnType("boolean")
                        .HasColumnName("forecast_period");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsAudited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_audited");

                    b.Property<bool>("PreviousPeriod")
                        .HasColumnType("boolean")
                        .HasColumnName("previous_period");

                    b.Property<long>("TraceNo")
                        .HasColumnType("BIGINT")
                        .HasColumnName("trace_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("Uri");

                    b.Property<bool>("YearlyForecastPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("yearly_forecast_period")
                        .HasDefaultValueSql("false");

                    b.Property<long>("symbol_id")
                        .HasColumnType("bigint")
                        .HasColumnName("symbol_id");

                    b.ComplexProperty<Dictionary<string, object>>("FiscalYear", "Fundamental.Domain.Codals.Manufacturing.Entities.NonOperationIncomeAndExpense.FiscalYear#FiscalYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Year")
                                .HasColumnType("SMALLINT")
                                .HasColumnName("fiscal_year");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Fundamental.Domain.Codals.Manufacturing.Entities.NonOperationIncomeAndExpense.Value#SignedCodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("value");
                        });

                    b.HasKey("_id")
                        .HasName("pk_non_operation_income_expense");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_non_operation_income_expense_id");

                    b.HasIndex("symbol_id")
                        .HasDatabaseName("ix_non_operation_income_expense_symbol_id");

                    b.ToTable("non-operation-income-expense", "manufacturing");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Publisher", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<string>("ActivitySubject")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("activity_subject");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<string>("AuditorName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("auditor_name");

                    b.Property<string>("CodalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("codal_id");

                    b.Property<CompanyType>("CompanyType")
                        .HasColumnType("company_type")
                        .HasColumnName("company_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<IsoCurrency>("Currency")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("iso_currency")
                        .HasColumnName("currency");

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("email");

                    b.Property<string>("ExecutiveManager")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("executive_manager");

                    b.Property<string>("FactoryFax")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("factory_fax");

                    b.Property<string>("FactoryTel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("factory_tel");

                    b.Property<string>("FaxNo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("fax_no");

                    b.Property<string>("FinancialManager")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("financial_manager");

                    b.Property<string>("FinancialYear")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("financial_year");

                    b.Property<PublisherFundType>("FundType")
                        .HasColumnType("publisher_fund_type")
                        .HasColumnName("fund_type");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<string>("Inspector")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("inspector");

                    b.Property<EnableSubCompany>("IsEnableSubCompany")
                        .HasColumnType("enable_sub_company")
                        .HasColumnName("is_enable_sub_company");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsSupplied")
                        .HasColumnType("boolean")
                        .HasColumnName("is_supplied");

                    b.Property<string>("Isic")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("isic");

                    b.Property<PublisherMarketType>("MarketType")
                        .HasColumnType("publisher_market_type")
                        .HasColumnName("market_type");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("national_code");

                    b.Property<string>("OfficeAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("office_address");

                    b.Property<string>("OfficeFax")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("office_fax");

                    b.Property<string>("OfficeTel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("office_tel");

                    b.Property<ReportingType>("ReportingType")
                        .HasColumnType("reporting_type")
                        .HasColumnName("reporting_type");

                    b.Property<string>("ShareOfficeAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("share_office_address");

                    b.Property<string>("ShareOfficeFax")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("share_office_fax");

                    b.Property<string>("ShareOfficeTel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("share_office_tel");

                    b.Property<PublisherState>("State")
                        .HasColumnType("publisher_state")
                        .HasColumnName("state");

                    b.Property<PublisherSubCompanyType>("SubCompanyType")
                        .HasColumnType("publisher_sub_company_type")
                        .HasColumnName("sub_company_type");

                    b.Property<string>("TelNo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("tel_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("website");

                    b.Property<long?>("parent-symbol-id")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_symbol_id");

                    b.Property<long>("symbol-id")
                        .HasColumnType("bigint")
                        .HasColumnName("symbol_id");

                    b.ComplexProperty<Dictionary<string, object>>("ListedCapital", "Fundamental.Domain.Codals.Publisher.ListedCapital#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("listed_capital");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnauthorizedCapital", "Fundamental.Domain.Codals.Publisher.UnauthorizedCapital#CodalMoney", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<IsoCurrency>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("iso_currency")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(36, 10)
                                .HasColumnType("decimal")
                                .HasColumnName("unauthorized_capital");
                        });

                    b.HasKey("_id")
                        .HasName("pk_publisher");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_publisher_id");

                    b.HasIndex("parent-symbol-id")
                        .HasDatabaseName("ix_publisher_parent_symbol_id");

                    b.HasIndex("symbol-id")
                        .HasDatabaseName("ix_publisher_symbol_id");

                    b.ToTable("publisher", "fs");
                });

            modelBuilder.Entity("Fundamental.Domain.ExAreas.Entities.Fair", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id")
                        .HasName("pk_fair");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_fair_id");

                    b.ToTable("fair", "ex_areas");
                });

            modelBuilder.Entity("Fundamental.Domain.Prices.Entities.ClosePrice", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<long>("Close")
                        .HasColumnType("bigint")
                        .HasColumnName("close");

                    b.Property<long>("CloseAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("close_adjusted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("Date")
                        .HasColumnName("date");

                    b.Property<long>("High")
                        .HasColumnType("bigint")
                        .HasColumnName("high");

                    b.Property<long>("HighAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("high_adjusted");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<long>("Last")
                        .HasColumnType("bigint")
                        .HasColumnName("last");

                    b.Property<long>("LastAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("last_adjusted");

                    b.Property<long>("Low")
                        .HasColumnType("bigint")
                        .HasColumnName("low");

                    b.Property<long>("LowAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("low_adjusted");

                    b.Property<long>("Open")
                        .HasColumnType("bigint")
                        .HasColumnName("open");

                    b.Property<long>("OpenAdjusted")
                        .HasColumnType("bigint")
                        .HasColumnName("open_adjusted");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.Property<long>("symbol_id")
                        .HasColumnType("bigint")
                        .HasColumnName("symbol_id");

                    b.HasKey("_id")
                        .HasName("pk_close_price");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_close_price_id");

                    b.HasIndex("symbol_id")
                        .HasDatabaseName("ix_close_price_symbol_id");

                    b.ToTable("close-price", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.Symbol", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<string>("CompanyEnCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_en_code");

                    b.Property<string>("CompanyIsin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_isin");

                    b.Property<string>("CompanyPersianName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_persian_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("en_name");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsUnOfficial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_un_official");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("isin");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint")
                        .HasColumnName("market_cap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<short>("ProductType")
                        .HasColumnType("smallint")
                        .HasColumnName("product_type");

                    b.Property<string>("SectorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sector_code");

                    b.Property<string>("SubSectorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_sector_code");

                    b.Property<string>("SymbolEnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("symbol_en_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("TseInsCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tse_ins_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id")
                        .HasName("pk_symbol");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_symbol_id");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasDatabaseName("ix_symbol_isin");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_symbol_name");

                    b.ToTable("symbol", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.SymbolRelation", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Ratio")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("ratio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<long>("child-id")
                        .HasColumnType("bigint")
                        .HasColumnName("child_id");

                    b.Property<long>("parent-id")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.HasKey("_id")
                        .HasName("pk_symbol_relation");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_symbol_relation_id");

                    b.HasIndex("child-id")
                        .HasDatabaseName("ix_symbol_relation_child_id");

                    b.HasIndex("parent-id")
                        .HasDatabaseName("ix_symbol_relation_parent_id");

                    b.ToTable("symbol-relation", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.SymbolShareHolder", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<short>("ReviewStatus")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("review_status");

                    b.Property<string>("ShareHolderName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("share_holder_name");

                    b.Property<short>("ShareHolderSource")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("share_holder_source");

                    b.Property<decimal>("SharePercentage")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasColumnName("share_percentage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Timestamp")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("share-holder-symbol-id")
                        .HasColumnType("bigint")
                        .HasColumnName("share_holder_symbol_id");

                    b.Property<long>("symbol-id")
                        .HasColumnType("bigint")
                        .HasColumnName("symbol_id");

                    b.HasKey("_id")
                        .HasName("pk_symbol_share_holders");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_symbol_share_holders_id");

                    b.HasIndex("share-holder-symbol-id")
                        .HasDatabaseName("ix_symbol_share_holders_share_holder_symbol_id");

                    b.HasIndex("symbol-id")
                        .HasDatabaseName("ix_symbol_share_holders_symbol_id");

                    b.ToTable("symbol-share-holders", "shd");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.FinancialStatement", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("symbol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_financial_statement_symbols_symbol_id");

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "ReportMonth", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint")
                                .HasColumnName("_id");

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("report_month");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("financial-statement", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id")
                                .HasConstraintName("fk_financial_statement_financial_statement__id");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "YearEndMonth", b1 =>
                        {
                            b1.Property<long>("FinancialStatement_id")
                                .HasColumnType("bigint")
                                .HasColumnName("_id");

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("year_end_month");

                            b1.HasKey("FinancialStatement_id");

                            b1.ToTable("financial-statement", "fs");

                            b1.WithOwner()
                                .HasForeignKey("FinancialStatement_id")
                                .HasConstraintName("fk_financial_statement_financial_statement__id");
                        });

                    b.Navigation("ReportMonth")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("YearEndMonth")
                        .IsRequired();
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.BalanceSheet", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("symbol-id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_balance_sheet_symbols_symbol_id");

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "ReportMonth", b1 =>
                        {
                            b1.Property<long>("BalanceSheet_id")
                                .HasColumnType("bigint")
                                .HasColumnName("_id");

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("report-month");

                            b1.HasKey("BalanceSheet_id");

                            b1.ToTable("balance-sheet", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("BalanceSheet_id")
                                .HasConstraintName("fk_balance_sheet_balance_sheet__id");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "YearEndMonth", b1 =>
                        {
                            b1.Property<long>("BalanceSheet_id")
                                .HasColumnType("bigint")
                                .HasColumnName("_id");

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("year-end-month");

                            b1.HasKey("BalanceSheet_id");

                            b1.ToTable("balance-sheet", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("BalanceSheet_id")
                                .HasConstraintName("fk_balance_sheet_balance_sheet__id");
                        });

                    b.Navigation("ReportMonth")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("YearEndMonth")
                        .IsRequired();
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.IncomeStatement", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("symbol-id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_income_statement_symbols_symbol_id");

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "ReportMonth", b1 =>
                        {
                            b1.Property<long>("IncomeStatement_id")
                                .HasColumnType("bigint")
                                .HasColumnName("_id");

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("report-month");

                            b1.HasKey("IncomeStatement_id");

                            b1.ToTable("income-statement", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("IncomeStatement_id")
                                .HasConstraintName("fk_income_statement_income_statement__id");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "YearEndMonth", b1 =>
                        {
                            b1.Property<long>("IncomeStatement_id")
                                .HasColumnType("bigint")
                                .HasColumnName("_id");

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("year-end-month");

                            b1.HasKey("IncomeStatement_id");

                            b1.ToTable("income-statement", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("IncomeStatement_id")
                                .HasConstraintName("fk_income_statement_income_statement__id");
                        });

                    b.Navigation("ReportMonth")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("YearEndMonth")
                        .IsRequired();
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.MonthlyActivity", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("symbol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monthly_activity_symbols_symbol_id");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Manufacturing.Entities.NonOperationIncomeAndExpense", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("symbol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_non_operation_income_expense_symbols_symbol_id");

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "ReportMonth", b1 =>
                        {
                            b1.Property<long>("NonOperationIncomeAndExpense_id")
                                .HasColumnType("bigint")
                                .HasColumnName("_id");

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("report_month");

                            b1.HasKey("NonOperationIncomeAndExpense_id");

                            b1.ToTable("non-operation-income-expense", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("NonOperationIncomeAndExpense_id")
                                .HasConstraintName("fk_non_operation_income_expense_non_operation_income_expense__");
                        });

                    b.OwnsOne("Fundamental.Domain.Codals.ValueObjects.StatementMonth", "YearEndMonth", b1 =>
                        {
                            b1.Property<long>("NonOperationIncomeAndExpense_id")
                                .HasColumnType("bigint")
                                .HasColumnName("_id");

                            b1.Property<short>("Month")
                                .HasColumnType("smallint")
                                .HasColumnName("year_end_month");

                            b1.HasKey("NonOperationIncomeAndExpense_id");

                            b1.ToTable("non-operation-income-expense", "manufacturing");

                            b1.WithOwner()
                                .HasForeignKey("NonOperationIncomeAndExpense_id")
                                .HasConstraintName("fk_non_operation_income_expense_non_operation_income_expense__");
                        });

                    b.Navigation("ReportMonth")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("YearEndMonth")
                        .IsRequired();
                });

            modelBuilder.Entity("Fundamental.Domain.Codals.Publisher", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "ParentSymbol")
                        .WithMany()
                        .HasForeignKey("parent-symbol-id")
                        .HasConstraintName("fk_publisher_symbols_parent_symbol_id");

                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("symbol-id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publisher_symbols_symbol_id");

                    b.Navigation("ParentSymbol");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Fundamental.Domain.Prices.Entities.ClosePrice", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("symbol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_close_price_symbols_symbol_id");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.SymbolRelation", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Child")
                        .WithMany("InvestorSymbols")
                        .HasForeignKey("child-id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_symbol_relation_symbol_child_id");

                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Parent")
                        .WithMany("InvestmentSymbols")
                        .HasForeignKey("parent-id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symbol_relation_symbol_parent_id");

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.SymbolShareHolder", b =>
                {
                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "ShareHolderSymbol")
                        .WithMany()
                        .HasForeignKey("share-holder-symbol-id")
                        .HasConstraintName("fk_symbol_share_holders_symbol_share_holder_symbol_id");

                    b.HasOne("Fundamental.Domain.Symbols.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("symbol-id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symbol_share_holders_symbol_symbol_id");

                    b.Navigation("ShareHolderSymbol");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.Symbol", b =>
                {
                    b.Navigation("InvestmentSymbols");

                    b.Navigation("InvestorSymbols");
                });
#pragma warning restore 612, 618
        }
    }
}
