// <auto-generated />
using System;
using Fundamental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fundamental.Migrations.Fundamental
{
    [DbContext(typeof(FundamentalDbContext))]
    partial class FundamentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fundamental.Domain.Symbols.Entities.Symbol", b =>
                {
                    b.Property<long>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("_id"), 1L, 1);

                    b.Property<string>("CompanyEnCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyEnCode");

                    b.Property<string>("CompanyIsin")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyIsin");

                    b.Property<string>("CompanyPersianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CompanyPersianName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EnName");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Isin");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint")
                        .HasColumnName("MarketCap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<short>("ProductType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ProductType")
                        .HasDefaultValueSql("1");

                    b.Property<string>("SectorCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SectorCode");

                    b.Property<string>("SubSectorCode")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SubSectorCode");

                    b.Property<string>("SymbolEnName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SymbolEnName");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.Property<string>("TseInsCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TseInsCode");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Isin")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Symbols", "shd");
                });
#pragma warning restore 612, 618
        }
    }
}
