//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundamental.Infrastructure.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonErrors
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonErrors()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fundamental.Infrastructure.Resources.CommonErrors", typeof(CommonErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to __message__.
        /// </summary>
        internal static string _00_000_800
        {
            get
            {
                return ResourceManager.GetString("00_000_800", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your account has been banned. Please contact support for more details..
        /// </summary>
        internal static string _00_000_801
        {
            get
            {
                return ResourceManager.GetString("00_000_801", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SsoSession is expired..
        /// </summary>
        internal static string _00_000_805
        {
            get
            {
                return ResourceManager.GetString("00_000_805", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SsoSession is revoked..
        /// </summary>
        internal static string _00_000_806
        {
            get
            {
                return ResourceManager.GetString("00_000_806", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The IDs in the route and the request body must be the same..
        /// </summary>
        internal static string _00_000_807
        {
            get
            {
                return ResourceManager.GetString("00_000_807", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internal server error. Please try again later..
        /// </summary>
        internal static string default_error_message
        {
            get
            {
                return ResourceManager.GetString("default_error_message", resourceCulture);
            }
        }
    }
}
