//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundamental.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Statements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Statements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fundamental.Infrastructure.Resources.Statements", typeof(Statements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Activity not found..
        /// </summary>
        internal static string _13_394_101 {
            get {
                return ResourceManager.GetString("13_394_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Statement not found..
        /// </summary>
        internal static string _13_395_101 {
            get {
                return ResourceManager.GetString("13_395_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol not found.
        /// </summary>
        internal static string _13_398_101 {
            get {
                return ResourceManager.GetString("13_398_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The traceno already exists..
        /// </summary>
        internal static string _13_398_102 {
            get {
                return ResourceManager.GetString("13_398_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A statement with the same year and month exists..
        /// </summary>
        internal static string _13_398_103 {
            get {
                return ResourceManager.GetString("13_398_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol not found.
        /// </summary>
        internal static string _13_399_101 {
            get {
                return ResourceManager.GetString("13_399_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The traceno already exists..
        /// </summary>
        internal static string _13_399_102 {
            get {
                return ResourceManager.GetString("13_399_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A statement with the same year and month exists..
        /// </summary>
        internal static string _13_399_103 {
            get {
                return ResourceManager.GetString("13_399_103", resourceCulture);
            }
        }
    }
}
