using Fundamental.ErrorHandling.Attributes;
using Fundamental.ErrorHandling.Enums;

namespace Fundamental.Application.Codals.Manufacturing.Jobs.UpdateTheStatusOfViableCompanyData;

[HandlerCode(HandlerCode.UpdateTheStatusOfViableCompany)]
public enum UpdateTheStatusOfViableCompanyErrorCodes;